databases:
  mainDatabase:
    enabled: true
    connectionString: "Server=YarTrader-prod-sql;Database=YarTraderDb;Trusted_Connection=True;"
  archiveDatabase:
    enabled: true
    connectionString: "Server=YarTrader-prod-sql;Database=YarTraderArchiveDb;Trusted_Connection=True;"
